### ISSUE TITLE
Das SQL-Feld zur Einschränkung der Werte um Insert-tags erweitern

### ISSUE THREAD

**Issue by davidmaack** [MetaModels/attribute_select#13]
Es wäre ein super Feature, wenn man in dem SQL-Feld, in dem man die Werte für das Select einschränken kann auf Insert-Tag zurückgreifen kann um z.B. auf die Werte von anderen Attributen zuzugreifen.

Somit können Select-Felder in Abhängigkeit zu anderen Attributen gebracht werden, das die Pflege der im BE deutlich leichter machen würde.

Ein gute Beispiel sind z.B. Die Felder "Land" und "Bundesland". Ist ein Land ausgewählt, werden nur die entsprechenden Bundesländer angezeigt.

**Comment by inred-froehlich** [comment]
Wird es in select auch kommen? Bräuchte diese Funktion sehr dringend.
Danke und lg

**Comment by discordier** [comment]
https://github.com/psren/attribute_select/commit/fb73458dab36ea058c749685caba94e923f5a810 started it a long time ago.

**Comment by xantippe** [comment]
Im Attribut "Select" gibt es (inzwischen?) die Option "Filter", mit der man bestimmte Einschränkungen ausführen kann - das sollte doch den Wunsch bzw. Fragestellung lösen => oder?

Hier wäre eher die Frage, ob bei Attribut Mehrfachauswahl [tags] nicht die Option "Filter" mit rein sollte...

**Comment by xantippe** [comment]
In Select gibt es die Filterauswahl - s.u.

das Ticket dürfte damit erledigt sein - oder?

![shot101](https://cloud.githubusercontent.com/assets/1045318/13120856/e0022ee6-d5af-11e5-91b4-dd8cf0b3d762.jpg)

**Comment by davidmaack** [comment]
Yupp würde ich auch so sagen. Bin mir gerade nicht sicher, ob man aktuell schon den Fall von Land => Bundeland damit abbilden könnte, aber das wäre dann auch eher ein Ticket bei den Filtern, oder nicht?

**Comment by xantippe** [comment]
wäre was bei Filter - sollte aber umsetzbar sein...
