### ISSUE TITLE
Readonly set false html attribute

### ISSUE THREAD

**Issue by Munsio** [MetaModels/attribute_select#18]
If i set an select attribute to readonly for the backend input mask the select get rendered with an readonly attribute instead of disabled

**Comment by xantippe** [comment]
siehe auch https://github.com/MetaModels/core/issues/567

**Comment by zonky2** [comment]
see https://github.com/contao-community-alliance/dc-general/issues/414

**Comment by zonky2** [comment]
fixed 

![screenshot_893](https://user-images.githubusercontent.com/1045318/77992703-e4a21380-7326-11ea-80d2-3d4161d4a3ae.png)
