### ISSUE TITLE
Filter liefert falsche Anzahl der Items

### ISSUE THREAD

**Issue by MacKP** [MetaModels/attribute_select#19]
Im Filter wird mir leider nur immer 1 als Wert ausgegeben (Anzahl der Items).
Filter geht auf einen Hierarchischen MM.

**Comment by zonky2** [comment]
siehe "Sammelticket" https://github.com/MetaModels/core/issues/312

**Comment by zonky2** [comment]
check https://github.com/MetaModels/attribute_select/pull/62
