### ISSUE TITLE
Select-Optionen selber definieren.

### ISSUE THREAD

**Issue by tognit** [MetaModels/attribute_select#20]
Könnte man die Möglichkeit einbauen, dass man beim attribute_select (attribute_translatedselect) die Optionen für die Auswahl selber eintragen kann? So das man nicht nur auf eine zweite DB-Tabelle zugreifen müsste.

![select-optionen](https://cloud.githubusercontent.com/assets/1794459/4023095/91c0655e-2b74-11e4-9ce9-dbe47d6a7e27.jpg)

**Comment by zonky2** [comment]
Entweder man speichert das als serialisierte Werte ab und kann dann nicht mehr mit SQl filtern oder man speichert dass dan in einer eigenen Tabelle ab ... da wäre man dann wieder an der selben Stelle - insbesondere dann, wenn man auch noch mehrsprachig arbeiten will.

Man kann solche "Hilfs-Angaben" auch gut in einem hierarchischem Model oder in zwei Models (Kategorie + Werte) & Filterung unterbringen.
