### ISSUE TITLE
Darstellung als Popup Picker mit Fehler

### ISSUE THREAD

**Issue by Kahmoon** [MetaModels/attribute_select#22]
Ich habe noch einen Bug gefunden. Wenn man das Selectfeld in der Eingabemaske als "Display as picker popup" definiert läd er bei einer Auswahl die Seite neu. Leider greift dann die Einstellung bzw. Prüfung der Sichtbarkeit eines Attributs/Feldes nicht.

Beispiel:
Zeige mit das Textfeld XY nur wenn Kategorie ist "Kategorie A". Nimmt man das Feld als Standard Selectbox wird das Feld bei der entsprechenden Kategorie angezeigt. Allerdings erst wenn man die Seite neu lädt oder speichert. Bei Select als Radiobutton funktioniert es ebenfalls...allerdings nicht ohne manuellen Reload. Wählt man die Darstellung als Picker Popup lädt er die Seite bei der Auswahl neu, was super ist und ich genau das brauche, aber die Kondition trifft nicht zu und er zeigt das Feld nicht an.  Auch nicht wenn ich den Datensatz mit der zutreffenden Kategorie speichere.

Falls das relevant ist. Das Feld KAtegorie zieht sich die Daten per "Auswahl" aus einem anderen Metamodel.

Screenshot im Forum https://community.contao.org/de/showthread.php?52466-Herangehensweise-f%FCr-Stadtportal-bei-MM&p=338561#post338561

VG
Frank

**Comment by xantippe** [comment]
sollte mit https://github.com/xantippe/dc-general/commit/1ef3684e5c04795a09625f21d8bfd34ff05f218c gefixt sein

**Comment by discordier** [comment]
Fixed in beta 34 with https://github.com/contao-community-alliance/dc-general/commit/d169f0dbcf4ccef8cc6c6ea643b5282a1bc3f3f2
