### ISSUE TITLE
Select-Filter filtert nicht richtig...

### ISSUE THREAD

**Issue by kein-nickname** [MetaModels/attribute_select#29]
Contao 3.34 / neuste TNG

Fehler beim Filtern von Select-Items
Bin mir nicht ganz sicher ob es in filter_select oder hier hin gehört!

Folgende Attribute:
1 x Select Item Bereich (A, B, C)
1 x Select Item Format (rund, eckig, oval)
1 x Tags Item Farbe zur Mehrfachauswahl  (rot, grün, gelb)

Unter Filter:
Eine SQL-Auswahl wo ich nur Datensätze aus dem Bereich A anzeigen lassen will
bzw. Einfach-Auswahl für Attribut bereich (URL-Parameter: A)
Mehrfachauswahl [Farbe]
Mehrfachauswahl [Format]

Ich erstelle 3 Datensätze mit dem ITEM Bereich A
Datensatz mit rot und rund
Datensatz mit rot und eckig
Datensatz mit grün und rund

und 1 Datensatz mit dem ITEM Bereich B
Datensatz mit gelb und rund

Wenn ich nun die Filter auf der Homepage nutze passiert folgendes:
Bei Farbe erscheint:
- rot (2)
- grün (1)

kein gelb (stimmt, da Gelb ja im Bereich B liegt und ausgefiltert wird)

Bei Format
- rund ()
- eckig ()
- oval ()

Es wird erstens keine Zahl angezeigt und zweitens wird der Bereich B nicht ausgefiltert.
Es scheint also ein Bug zu geben der beim Select-Filter existiert!

**Comment by discordier** [comment]
892a570e3ed2bc9d703f797bb1a8c3a69db18c48 behebt schon mal das Problem mit der Anzahl.

Bestehen die anderen Probleme auch noch?

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@kein-nickname could you please have a final look at this and tell if your issue has been resolved?
