### ISSUE TITLE
2 von 3 Darstellungsarten kaputt: Nur Picker funktioniert

### ISSUE THREAD

**Issue by psren** [MetaModels/attribute_select#39]
Ich nutze das Select mit übersetzbaren Feldern.
Die IDs im Select funktionieren, aber die Label werden nicht korrekt angezeigt.

So funktioniert es:
![bildschirmfoto 2015-03-03 um 17 10 35](https://cloud.githubusercontent.com/assets/1016798/6466723/f85db5d2-c1c9-11e4-9579-1c7cde73d128.png)

Bei den Select-Feldern klappt das nicht mehr, ebenso wie bei der Radiobutton-Menu
![bildschirmfoto 2015-03-03 um 17 09 56](https://cloud.githubusercontent.com/assets/1016798/6466724/f85ee8bc-c1c9-11e4-8e64-4683cef5aa99.png)
![bildschirmfoto 2015-03-03 um 16 17 44](https://cloud.githubusercontent.com/assets/1016798/6466727/fbb7e00e-c1c9-11e4-869b-b917396b927e.png)

**Comment by xantippe** [comment]
alle drei Varianten funktionieren
MM 2.0.0alpha10

![shot102](https://cloud.githubusercontent.com/assets/1045318/13121419/87ba0814-d5b2-11e5-96d8-2fa83bed1e78.jpg)
