### ISSUE TITLE
Select as radio ignores mandatory setting

### ISSUE THREAD

**Issue by Aybee** [MetaModels/attribute_select#42]
- Contao 3.4.5
- three minor extensions (deactivated)
- Nightly from 12.05.2015
- metamodels/attribute_select dev-tng @ ae05cf 2015-05-04 22:18:04

Attribut select mit 2 Werten aus anderem MetaModel. Wenn das Feld in der Eingabemaske auf Pflicht gesetzt ist bekommt man beim Speichern keine Fehlermeldung wenn man keine Auswahl trifft. Mit oder ohne `include blank option` ist egal.

Der Fehler ist nur beim Typ `select as radio` nicht bei `as select menu` oder `as picker popup`

**Comment by discordier** [comment]
Is the mandatory eval populated? It appears that the `RadioWidget` handles it correctly https://github.com/contao/core/blob/b79bebca663fc1b277c7023da95ffaaa66ab4910/system/modules/core/widgets/RadioButton.php#L48 Have not checked the validator though.

**Comment by Aybee** [comment]
Yes, I think it's populated.
```html
<div class="widget w50 w50x" id="widget_business">
  <input type="hidden" name="FORM_INPUTS[]" value="business">
  <fieldset class="tl_radio_container mandatory" id="ctrl_business">
    <legend>
      <span class="invisible">Pflichtfeld</span> Business<span class="mandatory">*</span>
    </legend>
    <input type="radio" onfocus="Backend.getScrollOffset()" value="Einzelhandel" class="tl_radio" id="opt_business_0" name="business">
    <label for="opt_business_0">Einzelhandel</label>
    <br>
    <input type="radio" onfocus="Backend.getScrollOffset()" value="Gastronomie" class="tl_radio" id="opt_business_1" name="business">
    <label for="opt_business_1">Gastronomie</label>
  </fieldset>
  <p class="tl_help tl_tip" title="">Wählen Sie die Sparte/Branche/Kategorie/Geschäftszweig - Hieraus soll ein Filter erstellt werden.</p>
</div>
```
*Can someone please correct the topic? radion => radio, thank you.*

**Comment by discordier** [comment]
Ok, so this is strange then as the default `Widget::validator` is handling the mandatory flag.

Maybe DC_General is ignoring it somehow but then this should affect all widgets and not the `radio` only... I am a little confused now.

**Comment by Aybee** [comment]
Ok, so how can I help you? Update to C 3.5, update the latest nightly, BE-Access, FTP access, doing some tests? If you like to reproduce it you need
- An attribute single select
- An input mask mandatory as radio button list
- Create a MM dataset, fill all mandatory fields except the radio and save
- you'll see no error

If dataset once is saved with a radio selected, you only can test it, if you have a blank option to withdraw your previous setting. But then if you select the blank option the error message correctly appears.

So I think the problem only occurs when you create a new dataset and forget to select the radio.

**Comment by Aybee** [comment]
I'm working around this problem by using a select with a blank option instead the radios without a blank option. With a select the error message correctly occurs as soon as you save a new dataset without making a selection. 

But it does not depend on the blank option, if you use the radios with a blank option the error occurs anyway.

**Comment by xantippe** [comment]
I test it with MM 2.0.0alpha10 and works fine with radio buttons or popup picker

![shot102](https://cloud.githubusercontent.com/assets/1045318/13122291/8eaa7498-d5b6-11e5-95ec-5f58bc83f6b2.jpg)
