### ISSUE TITLE
Too few arguments in error message

### ISSUE THREAD

**Issue by pju-** [MetaModels/attribute_select#44]
class MetaModelSelect
File MetaModelSelect.php
Line 173

```php
sprintf(
    'Multiple values found for %s, are there obsolete values for %s.%s (att_id: %s)?',
    var_export($varValue, true),
    $model->getTableName(),
    $this->getColName()
)
```

There are four placeholders in the sprintf, but only three arguments following. This creates a warning:
````
Warning: sprintf(): Too few arguments in .../metamodelsattribute_select/classes/src/MetaModels/Attribute/Select/MetaModelSelect.php on line 178
````

I tried adding a fourth argument, but then it just silently fails instead of throwing an exception like it should?

I think this is a bug.

**Comment by discordier** [comment]
It is.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@pju- could you please have a final look at this and tell if your issue has been resolved?
