### ISSUE TITLE
Bild ausgabe im Frontend

### ISSUE THREAD

**Issue by BlackP999** [MetaModels/attribute_select#45]
Hallo,
habe eine Liste angelegt mit Auszeichnungen (jeweils mit Auszeichnungsname und einem Bild der Auszeichnung).
In der Frontend augabe wird der Auszeichnungsname als Text ausgegeben aber das Bild wird nur so ausgegeben: �!��Ee���=~�n

**Comment by MacKP** [comment]
Was genau hast du in den Rendersettings eingestellt?
By the way: sowas könntest du besser erst mal im Forum klären bevor du ein Ticket auf machst.

Viele Grüße

**Comment by BlackP999** [comment]
ups
sorry hast recht. Schliesse das Ticket ich schreibe ins Forum!

**Comment by MacKP** [comment]
OK, kannst das ja neu eröffnen, wenn es dann doch ein Problem ist, was in ein Ticket muss ;-)
Schreib im Forum am besten direkt deine Einstellungen etc.
