### ISSUE TITLE
sortIds function removed ID from list.

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/attribute_select#47]
I have a problem with the sortIds function. The function is called from the filter and the idList contains 21 entries after the sortId function i only have 2 in the list. So the filter works fine but the sort function removes id's from the list. The main problem is that not all items has a sleceted value and so the mapping list are most the time empty. See the code.

I fix this problem with a diff and merge. All sorted values are at the top of the list, all missing will be added after the sorted values. Is this the right place for this or should the core take care of this ?

```php 
        $diff = array_diff($idList, $result);
        return array_merge($result, $diff);
```

See https://github.com/MetaModels/attribute_select/blob/master/src/MetaModels/Attribute/Select/MetaModelSelect.php#L477
```php 
// $valueIds
array (size=21)
  4 => string '0' (length=1)
  26 => string '0' (length=1)
  28 => string '0' (length=1)
  29 => string '0' (length=1)
  30 => string '0' (length=1)
  40 => string '0' (length=1)
  42 => string '0' (length=1)
  45 => string '0' (length=1)
  47 => string '0' (length=1)
  25 => string '0' (length=1)
  48 => string '0' (length=1)
  23 => string '0' (length=1)
  14 => string '0' (length=1)
  10 => string '0' (length=1)
  9 => string '0' (length=1)
  5 => string '0' (length=1)
  8 => string '0' (length=1)
  7 => string '0' (length=1)
  6 => string '0' (length=1)
  24 => string '29' (length=2)
  31 => string '30' (length=2)

// $valueMap
array (size=3)
  0 => 
    array (size=19)
      0 => string '4' (length=1)
      1 => string '26' (length=2)
      2 => string '28' (length=2)
      3 => string '29' (length=2)
      4 => string '30' (length=2)
      5 => string '40' (length=2)
      6 => string '42' (length=2)
      7 => string '45' (length=2)
      8 => string '47' (length=2)
      9 => string '25' (length=2)
      10 => string '48' (length=2)
      11 => string '23' (length=2)
      12 => string '14' (length=2)
      13 => string '10' (length=2)
      14 => string '9' (length=1)
      15 => string '5' (length=1)
      16 => string '8' (length=1)
      17 => string '7' (length=1)
      18 => string '6' (length=1)
  29 => 
    array (size=1)
      0 => string '24' (length=2)
  30 => 
    array (size=1)
      0 => string '31' (length=2)

```

**Comment by stefanheimes** [comment]
@discordier, what do u think about this one. We have this bug all the time and nobody see it :)

**Comment by xantippe** [comment]
@stefanheimes sollte es nicht sowieso mal eine konfigurierbare Sortiermöglichkeit geben? siehe https://github.com/MetaModels/core/issues/74

**Comment by stefanheimes** [comment]
@xantippe  this is not the quest at the moment, we have a huge bug which removes id from the current filter list. please first the fix than the discussion if or if not. 

Btw this is the sorting of items of the MetaModel list for the content elements and not the one for the filter list and filter content element. :)

**Comment by xantippe** [comment]
o.k.!

**Comment by discordier** [comment]
@stefanheimes good solution, should have no negative side effects. However I feel we must check and apply it to other attributes as well.

**Comment by stefanheimes** [comment]
Should be fixed with e8d8bcbaaaf121de4cb07d6ae17ae32535004f7e.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@stefanheimes could you please have a final look at this and tell if your issue has been resolved?

**Comment by discordier** [comment]
@stefanheimes could you please add unit tests next time? :)
