### ISSUE TITLE
mit Fix #50 funktioniert nicht (mehr) für Sub-Paletten/Ansichtsbedingungen

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_select#52]
siehe https://github.com/MetaModels/attribute_select/issues/50#issuecomment-186106999

**Comment by zonky2** [comment]
in MM core hotfix-alpha11 gefixt
https://github.com/MetaModels/core/commit/c96762923b102eab7ca753fcfeb5332f9ec2e860

Test:
Einstellungen

![shot190](https://cloud.githubusercontent.com/assets/1045318/15009009/56cfa9de-11e4-11e6-812c-c5af8eefe79f.jpg)

Anzeige - keine Anzeige von Vorname
![shot191](https://cloud.githubusercontent.com/assets/1045318/15009035/6e499912-11e4-11e6-954c-01b7d2884cda.jpg)

Anzeige - Anzeige von Vorname
![shot192](https://cloud.githubusercontent.com/assets/1045318/15009045/7a2c46c6-11e4-11e6-807c-6c1253017f73.jpg)

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@zonky2 could you please have a final look at this and tell if your issue has been resolved?
