### ISSUE TITLE
Attributbezeichnung bei Tabellenansicht im BE nicht angezeigt, wenn in Eingabemaske ausgeblendet

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_select#53]
Attributbezeichnung bei Tabellenansicht im BE nicht angezeigt, wenn in Eingabemaske ausgeblendet/ nicht aktiv bzw. nicht vorhanden ist

![shot145](https://cloud.githubusercontent.com/assets/1045318/13494354/f3f5924a-e143-11e5-9e96-9b908315daf2.jpg)

**Comment by xantippe** [comment]
Korrektur zum Bug: die Überschrift wird nicht angezeigt, wenn das Feld in der Eingabemaske ausgeblendet/ nicht aktiv bzw. nicht vorhanden ist

**Comment by zonky2** [comment]
@discordier ist ticket fixed with your update at DCG?

**Comment by discordier** [comment]
You tell me, but I suspect it is not.

**Comment by zonky2** [comment]
o.k. its fixed!
![shot313](https://cloud.githubusercontent.com/assets/1045318/22019868/97037aac-dcb5-11e6-8772-bf8b7576b9ec.jpg)
