### ISSUE TITLE
Wenn die Option Pflichtfeld nicht aktiviert ist wird der Wert nicht mehr gespeichert 

### ISSUE THREAD

**Issue by palmi** [MetaModels/attribute_select#60]
## Checklist before I submit this issue report

I confirm that:
- [ ] I have tested this with the latest version available
- [ ] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [ ] I have checked the Contao community forums for references https://community.contao.org/
- [ ] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_select/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |          |                                  |
| Contao version:                     |          |                                  |
| MetaModels version:                 |          |                                  |
| Installation via composer           | (yes/no) |                                  |
| Installed MetaModels packages       |          |                                  |

## Issue description

(Describe the problem you are having)

## Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on…]

## Describe the behaviour of the application

(Tell us what happens)

## Describe the expected behaviour of the application

(Tell us what should have happened)

## Screenshots

(Add some visual love or even a video if you can)

**Comment by palmi** [comment]
Wenn die Option Pflichtfeld nicht aktiviert ist wird der Wert nicht mehr gespeichert.
Wert = ID
seit letzen Update funktioniert es nicht mehr

**Comment by zonky2** [comment]
korrekt! wie immer: Bugliste im Forum lesen und Issues auf Github durchsehen
